name: Publish Docker image
on:
  workflow_dispatch:
    inputs:
      msg:
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository:  devofcode123/sigidoc
          tags: latest
          dockerfile: Dockerfile
  deploy:
    name: Deploy image
    needs: push_to_registry
    runs-on: self-hosted
    steps:
      - name: Pull image
        run: docker pull ghcr.io/devofcode123/sigidoc:latest
      - name: Stop previous container
        run: docker stop sigidoc || true && docker rm sigidoc || true
      - name: Run image
        run: docker run -p 9000:9999 --rm --name sigidoc ghcr.io/devofcode123/sigidoc:latest
